services:
  polaris:
    image: ghcr.io/simon-ding/polaris:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIGURATION_FILE_LOCATION}/polaris:/app/data 
      - ${DOWNLOAD_LOCATION}:/downloads 
      - ${MEDIA_LOCATION}:/data 
    env_file:
      - .env
    ports:
      - 3322:8080
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIGURATION_FILE_LOCATION}/transmission:/config
      - ${DOWNLOAD_LOCATION}:/downloads 
    env_file:
      - .env
    restart: always
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIGURATION_FILE_LOCATION}/prowlar:/config
    env_file:
      - .env
    ports:
      - 9696:9696
    restart: always