name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write


jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3
      - name: Build Web
        run: |
          cd ui
          flutter pub get
          flutter build web --no-web-resources-cdn --web-renderer html
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'
          check-latest: true
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
